"""Install testboard into a Playwright test repository.

The application is deliberately **not** committed to the repository it manages. This script
materialises it into a gitignored `.testboard/venv`, and the repo commits only two small files:
`testboard.yaml` (everything specific to it) and `testboard.lock` (which version is installed).

That is the whole answer to "six repos, six divergent copies a year from now": there is nothing in
version control to diverge, and upgrading is re-running this script rather than reviewing a diff.
The vendored `scripts/*.py` in these repos are the counter-example — they are byte-identical only
for as long as somebody keeps checking.

    python install_testboard.py --repo path/to/test-repo
    python install_testboard.py --repo path/to/test-repo --upgrade
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

SOURCE = Path(__file__).resolve().parent.parent / "testboard"
GITIGNORE_LINES = ["", "# testboard", ".testboard/"]


def _log(message: str) -> None:
    # Re-encoded for the console we are actually on. A default Windows console is cp1252, and an
    # em dash printed into it comes out as a replacement character — which reads, to whoever is
    # installing, like the installer itself is broken.
    text = f"  {message}"
    encoding = getattr(sys.stdout, "encoding", None) or "utf-8"
    try:
        text.encode(encoding)
    except UnicodeEncodeError:
        text = text.replace("—", "-").replace("→", "->").replace("’", "'")
        text = text.encode(encoding, errors="replace").decode(encoding)
    print(text)


def venv_python(venv: Path) -> Path:
    candidate = venv / "Scripts" / "python.exe"
    return candidate if candidate.exists() or os.name == "nt" else venv / "bin" / "python"


def detect_repo_python(repo: Path) -> str:
    """Find the interpreter that runs the tests. Reported, never guessed silently."""
    for name in ("venv", ".venv", "env"):
        root = repo / name
        if (root / "Scripts" / "python.exe").exists() or (root / "bin" / "python").exists():
            return name
    return "venv"


def detect_test_paths(repo: Path) -> list[str]:
    pyproject = repo / "pyproject.toml"
    if pyproject.exists():
        text = pyproject.read_text(encoding="utf-8-sig")
        match = re.search(r"^\s*testpaths\s*=\s*\[([^\]]*)\]", text, re.M)
        if match:
            found = re.findall(r'["\']([^"\']+)["\']', match.group(1))
            if found:
                return found
    for candidate in ("e2e/tests", "tests", "e2e"):
        if (repo / candidate).is_dir():
            return [candidate]
    return ["tests"]


def detect_env_vars(repo: Path) -> tuple[str, list[str]]:
    """Read the conftest for the environment variables the suite actually consults."""
    names: list[str] = []
    for conftest in list(repo.glob("conftest.py")) + list(repo.glob("*/conftest.py")):
        text = conftest.read_text(encoding="utf-8", errors="replace")
        names += re.findall(r"""os\.environ(?:\.get)?[\(\[]\s*["']([A-Z0-9_]+)["']""", text)
    ordered = list(dict.fromkeys(names))
    base = next((n for n in ordered if "BASE_URL" in n or n.endswith("_URL")), "APP_BASE_URL")
    return base, [n for n in ordered if n != base]


def detect_markers(repo: Path) -> dict[str, str]:
    pyproject = repo / "pyproject.toml"
    registered: list[str] = []
    if pyproject.exists():
        text = pyproject.read_text(encoding="utf-8-sig")
        block = re.search(r"^\s*markers\s*=\s*\[(.*?)\]", text, re.M | re.S)
        if block:
            registered = [m.split(":")[0].strip()
                          for m in re.findall(r'["\']([^"\']+)["\']', block.group(1))]
    destructive = next((m for m in ("writes", "destructive", "mutates") if m in registered),
                       "writes")
    quarantine = next((m for m in ("quarantine", "stale") if m in registered), "quarantine")
    return {"destructive": destructive, "quarantine": quarantine,
            "registered": registered}  # type: ignore[dict-item]


def render_config(repo: Path) -> str:
    base_env, passthrough = detect_env_vars(repo)
    markers = detect_markers(repo)
    paths = detect_test_paths(repo)
    interpreter = detect_repo_python(repo)
    warn = "" if "quarantine" in markers["registered"] else (
        "\n# NOTE: the quarantine marker is not registered in pyproject.toml. With --strict-markers\n"
        "# set, using it will fail collection. Register it before quarantining anything.\n"
    )
    return f"""# testboard configuration for this repository.
#
# This file is the ONLY place a repo-specific fact may live. testboard's own code carries no path,
# URL or marker name belonging to any one repository, which is what makes upgrading it a version
# bump instead of a merge.
#
# Generated by install_testboard.py from what is actually in this repo. Read it before trusting
# it — the values below were inferred, not confirmed.
{warn}
schema_version: 1

repo:
  name: {repo.name}

runner:
  language: python
  framework: pytest
  python: {interpreter}
  test_paths: [{', '.join(paths)}]
  extra_args: []
  markers:
    destructive: {markers['destructive']}
    quarantine: {markers['quarantine']}
  timeouts:
    default_seconds: 900

environment:
  base_url_env: {base_env}
  passthrough_env: [{', '.join(passthrough)}]

drift:
  script: scripts/check_drift.py
  config: drift-config.json
  map: project-map.json
  map_age:
    warn_after_days: 14
    stale_after_days: 30

artifacts:
  retain_runs_per_test: 20
  retain_failed_traces_per_test: 10
  total_cap_mb: 5000
  disk_floor_mb: 500

safety:
  confirm_before_run: [{markers['destructive']}]
  never_batch: [{markers['destructive']}]

# Turning an uploaded recording into tests. Needs the Codex SDK and a credential:
#   pip install 'openai-codex'      and either `codex login` or CODEX_API_KEY in the environment.
# Without them the feature reports itself unavailable; nothing else is affected.
generation:
  enabled: true
  model:                                 # blank uses the account default
  sandbox: workspace_write               # read_only | workspace_write | full_access
  timeout_seconds: 3600
  skill:                                 # path to video-to-playwright; found automatically if unset
"""


def update_gitignore(repo: Path) -> bool:
    path = repo / ".gitignore"
    existing = path.read_text(encoding="utf-8") if path.exists() else ""
    if ".testboard/" in existing:
        return False
    path.write_text(existing.rstrip("\n") + "\n".join(GITIGNORE_LINES) + "\n", encoding="utf-8")
    return True


def install(repo: Path, upgrade: bool, with_codex: bool = False) -> int:
    if not SOURCE.is_dir():
        print(f"testboard source not found at {SOURCE}", file=sys.stderr)
        return 2

    version = re.search(r'version\s*=\s*"([^"]+)"',
                        (SOURCE / "pyproject.toml").read_text(encoding="utf-8"))
    version = version.group(1) if version else "unknown"

    print(f"Installing testboard {version} into {repo}")

    state = repo / ".testboard"
    venv = state / "venv"
    state.mkdir(parents=True, exist_ok=True)

    if not venv.exists():
        _log("creating .testboard/venv")
        subprocess.run([sys.executable, "-m", "venv", str(venv)], check=True)
    elif upgrade:
        _log("reusing .testboard/venv")

    python = venv_python(venv)

    # Upgrading pip is a convenience, not a requirement. It is also the step most likely to fail
    # for reasons that have nothing to do with testboard — a long path on Windows, an offline
    # machine, a proxy — so a failure here must not abort the install.
    upgrade_pip = subprocess.run(
        [str(python), "-m", "pip", "install", "--quiet", "--upgrade", "pip"],
        capture_output=True, text=True,
    )
    if upgrade_pip.returncode != 0:
        _log("could not upgrade pip in the new venv; continuing with the bundled version")

    _log("installing the package and its dependencies")
    spec = f"{SOURCE}[codex]" if with_codex else str(SOURCE)
    install_result = subprocess.run(
        [str(python), "-m", "pip", "install", "--quiet", "--upgrade", spec],
        capture_output=True, text=True,
    )
    if install_result.returncode != 0:
        print(install_result.stdout[-2000:], file=sys.stderr)
        print(install_result.stderr[-2000:], file=sys.stderr)
        print("\ntestboard could not be installed into the virtualenv (see above).",
              file=sys.stderr)
        return 1

    config = repo / "testboard.yaml"
    if config.exists():
        # Never touched once it exists. Whatever the person set is theirs, and a scaffold that
        # silently rewrites configuration is a scaffold nobody runs twice.
        _log("testboard.yaml already exists — left exactly as it is")
    else:
        config.write_text(render_config(repo), encoding="utf-8")
        _log("wrote testboard.yaml — review the inferred values")

    (repo / "testboard.lock").write_text(json.dumps({
        "version": version,
        "installed_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": str(SOURCE),
    }, indent=2) + "\n", encoding="utf-8")
    _log("wrote testboard.lock")

    if update_gitignore(repo):
        _log("added .testboard/ to .gitignore")

    print()
    print("Start it with:")
    rel = python.relative_to(repo) if python.is_relative_to(repo) else python
    print(f"  cd {repo}")
    print(f"  {rel} -m testboard")
    print()
    print("Commit testboard.yaml and testboard.lock. Do not commit .testboard/.")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--repo", required=True)
    parser.add_argument("--upgrade", action="store_true",
                        help="reinstall the package into an existing .testboard/venv")
    parser.add_argument("--with-codex", action="store_true",
                        help="also install the Codex SDK, so recordings can be turned into tests")
    args = parser.parse_args()

    repo = Path(args.repo).resolve()
    if not repo.is_dir():
        print(f"no such directory: {repo}", file=sys.stderr)
        return 2
    return install(repo, args.upgrade, args.with_codex)


if __name__ == "__main__":
    raise SystemExit(main())
